#!/bin/bash

set -e

export LOG_DIR=/var/vcap/sys/log/kafka
export RUN_DIR=/var/vcap/sys/run/kafka
export PIDFILE=/var/vcap/sys/run/kafka/pid
export TMPDIR=/var/vcap/data/kafka/tmp

source /var/vcap/packages/openjdk-1.8/bosh/runtime.env

case $1 in

  start)
    mkdir -p $LOG_DIR $RUN_DIR
    chown -R vcap:vcap $LOG_DIR $RUN_DIR

    echo $$ > $PIDFILE

    ulimit -n 100000

    exec chpst -u vcap:vcap \
      /var/vcap/packages/kafka/bin/kafka-server-start.sh \
      /var/vcap/jobs/kafka/config/server.properties \
      >>/var/vcap/sys/log/kafka/stdout.log \
      2>>/var/vcap/sys/log/kafka/stderr.log
    ;;

  stop)
    if [ -f $PIDFILE ]; then
      kill -9 `cat $PIDFILE` || true
      rm -f $PIDFILE
    fi
    ;;

  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;

esac
exit 0
