#!/bin/bash

export LOG_DIR=/var/vcap/sys/log/kafka
export RUN_DIR=/var/vcap/sys/run/kafka
export STORE_DIR=/var/vcap/store/kafka
export DATA_DIR=/var/vcap/data/kafka
export TMP_DIR=/var/vcap/data/kafka/tmp

for dir in $LOG_DIR $RUN_DIR $DATA_DIR $STORE_DIR $TMP_DIR; do
  mkdir -p ${dir}
  chown vcap:vcap ${dir}
  chmod 700 ${dir}
done

chown -R vcap:vcap ${STORE_DIR}
