#!/bin/bash

set -e

source /var/vcap/packages/openjdk-1.8/bosh/runtime.env

<% zk = link("zookeeper") %>

/var/vcap/packages/kafka/bin/kafka-topics.sh \
  --zookeeper "<%= zk.instances.map { |i| "#{i.address}:#{zk.p("client_port")}" }.join(",") %>" \
  $@
