---
name: kafka-user

releases:
- name: kafka
  version: 0.0.2
  url: git+https://github.com/cppforlife/kafka-release

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: user
  azs: [z1, z2, z3]
  instances: 1
  lifecycle: errand
  jobs:
  - name: create-user
    release: kafka
    consumes:
      zookeeper: {from: conn, deployment: zookeeper}
      topic: {from: topic, deployment: ((si_deployment_name))}
    properties:
      name: user-((user))
  - name: delete-user
    release: kafka
    consumes:
      zookeeper: {from: conn, deployment: zookeeper}
      topic: {from: topic, deployment: ((si_deployment_name))}
    properties:
      name: user-((user))
  vm_type: default
  stemcell: default
  networks:
  - name: default

variables:
- name: user
  type: password # todo ideally uuid
