#!/bin/bash

set -e

<% zk = link("zookeeper") %>

source /var/vcap/packages/openjdk-1.8/bosh/runtime.env

/var/vcap/packages/kafka/bin/kafka-topics.sh --delete \
  --zookeeper "<%= zk.instances.map { |i| "#{i.address}:#{zk.p("client_port")}" }.join(",") %>" \
  --topic <%= p("name") %> \
  --if-exists
